# Site Settings
title: "Sudev Sheth"
subtitle: "Author, Educator, & Historian"
email: "sudev@wharton.upenn.edu"
description: "Senior Lecturer at the University of Pennsylvania, historian of business, entrepreneurship, and South Asia."
baseurl: ""  # Leave empty since you're hosting at the root domain
url: "https://www.sudevsheth.com"  # Your custom domain
city: "Philadelphia"
state: "PA"

# Homepage Tiles
tiles-source: "pages"  # Accepts "posts" or "pages"
tiles-count: 4  # Increased count for more content visibility

# Social Settings (Icons must match Font Awesome names)
socials:
  GitHub: "https://github.com/sudevsheth"
  Google Scholar: "https://scholar.google.com/citations?user=ldgGoNYAAAAJ&hl=en"
  Amazon: "https://a.co/d/gzq6GjN"
  LinkedIn: "https://www.linkedin.com/in/sudev-sheth/"
  Twitter: "https://x.com/SudevSheth"

# Build Settings
markdown: kramdown

sass:
  style: compressed

# Exclude Files from Build Process
exclude:
  - "*.gemspec"
  - LICENSE.md
  - CONTRIBUTING.md
  - README.md
